openapi: 3.0.0
info:
  title: File API
  version: 1.0.0
  description: An API which collects lines from files

paths:
  /lines/{line_index}:
    get:
      summary: Get line from file
      operationId: getLineFromFile
      parameters:
        - name: line_index
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          $ref: '#/components/responses/GetLineSuccess200'
        '413':
          $ref: '#/components/responses/GetLineFailure413'
        '500':
          $ref: '#/components/responses/GetLineFailure500'

components:
  schemas:
    Line:
      type: object
      properties:
        content:
          type: string
          example: "I am the spark that ignites the flame."
    ErrorMessage:
      type: object
      properties:
        message:
          type: string
          example: "This is an example error!"

  responses:
    GetLineSuccess200:
      description: Successfully collect the line from the file
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Line'
    GetLineFailure413:
      description: Line is beyond the end of the file
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    GetLineFailure500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'